/**
 * Generates a static HTML/CSS project from a SiteIntentDocument.
 * Produces a file array that can be zipped for download.
 */

import type { SiteIntentDocument, ComponentPlacement } from "../assembly/spec.types";
import { generateThemeFromVector } from "../theme/generate-theme";
import { tokensToCSSProperties } from "../theme/token-map";
import type { PersonalityVector } from "../theme/theme.types";

export interface ExportFile {
  path: string;
  content: string;
}

export interface ExportResult {
  files: ExportFile[];
  businessName: string;
}

/**
 * Generate a standalone static project from the site spec.
 */
export function generateProject(spec: SiteIntentDocument): ExportResult {
  const tokens = generateThemeFromVector(spec.personalityVector as PersonalityVector, {
    businessType: spec.siteType,
  });
  const cssVars = tokensToCSSProperties(tokens);

  const cssContent = generateCSS(cssVars);
  const page = spec.pages[0];
  const htmlContent = generateHTML(spec.businessName, page?.components ?? [], cssVars);

  const files: ExportFile[] = [
    { path: "index.html", content: htmlContent },
    { path: "styles.css", content: cssContent },
    { path: "README.md", content: generateReadme(spec.businessName) },
  ];

  return { files, businessName: spec.businessName };
}

function generateCSS(cssVars: Record<string, string>): string {
  const varEntries = Object.entries(cssVars)
    .map(([key, value]) => `  ${key}: ${value};`)
    .join("\n");

  return `/* Generated by EasyWebsiteBuild */
/* Theme Variables */
:root {
${varEntries}
}

/* Reset & Base */
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  scroll-behavior: smooth;
}

body {
  font-family: var(--font-body);
  color: var(--color-text);
  background-color: var(--color-background);
  line-height: var(--leading-normal);
  -webkit-font-smoothing: antialiased;
}

img {
  max-width: 100%;
  height: auto;
  display: block;
}

a {
  color: var(--color-primary);
  text-decoration: none;
}

a:hover {
  opacity: 0.85;
}

/* Layout */
.container {
  max-width: var(--container-max, 1200px);
  margin: 0 auto;
  padding: 0 1.5rem;
}

.section {
  padding: var(--space-section, 5rem) 0;
}

.section--alt {
  background-color: var(--color-surface);
}

/* Navigation */
.nav {
  position: sticky;
  top: 0;
  z-index: 50;
  background-color: var(--color-background);
  border-bottom: 1px solid var(--color-border);
  padding: 1rem 0;
}

.nav .container {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.nav__logo {
  font-family: var(--font-heading);
  font-size: var(--text-xl);
  font-weight: var(--weight-bold);
  color: var(--color-text);
}

.nav__links {
  display: flex;
  gap: 2rem;
  list-style: none;
}

.nav__links a {
  color: var(--color-text-secondary);
  font-size: var(--text-sm);
  font-weight: var(--weight-medium);
  transition: color 0.2s;
}

.nav__links a:hover {
  color: var(--color-text);
}

.nav__cta {
  display: inline-flex;
  align-items: center;
  padding: 0.5rem 1.25rem;
  background-color: var(--color-primary);
  color: var(--color-text-on-primary);
  border-radius: var(--radius-md);
  font-size: var(--text-sm);
  font-weight: var(--weight-semibold);
  border: none;
  cursor: pointer;
  transition: opacity 0.2s;
}

.nav__cta:hover {
  opacity: 0.9;
  color: var(--color-text-on-primary);
}

/* Hero */
.hero {
  padding: 8rem 0 6rem;
  text-align: center;
}

.hero__headline {
  font-family: var(--font-heading);
  font-size: clamp(2.5rem, 5vw, 4rem);
  font-weight: var(--weight-bold);
  line-height: var(--leading-tight);
  letter-spacing: var(--tracking-tight);
  color: var(--color-text);
  margin-bottom: 1.5rem;
}

.hero__subheadline {
  font-size: var(--text-lg);
  color: var(--color-text-secondary);
  max-width: 640px;
  margin: 0 auto 2.5rem;
  line-height: var(--leading-relaxed);
}

.hero__actions {
  display: flex;
  gap: 1rem;
  justify-content: center;
  flex-wrap: wrap;
}

/* Buttons */
.btn-primary {
  display: inline-flex;
  align-items: center;
  padding: 0.75rem 2rem;
  background-color: var(--color-primary);
  color: var(--color-text-on-primary);
  border-radius: var(--radius-md);
  font-weight: var(--weight-semibold);
  font-size: var(--text-base);
  border: none;
  cursor: pointer;
  transition: opacity 0.2s;
}

.btn-primary:hover {
  opacity: 0.9;
  color: var(--color-text-on-primary);
}

.btn-outline {
  display: inline-flex;
  align-items: center;
  padding: 0.75rem 2rem;
  background: transparent;
  color: var(--color-text);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  font-weight: var(--weight-semibold);
  font-size: var(--text-base);
  cursor: pointer;
  transition: border-color 0.2s;
}

.btn-outline:hover {
  border-color: var(--color-primary);
  color: var(--color-text);
}

/* Features Grid */
.features-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 2rem;
}

.feature-card {
  padding: 2rem;
  background-color: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
}

.feature-card__title {
  font-family: var(--font-heading);
  font-size: var(--text-lg);
  font-weight: var(--weight-semibold);
  color: var(--color-text);
  margin-bottom: 0.5rem;
}

.feature-card__description {
  font-size: var(--text-sm);
  color: var(--color-text-secondary);
  line-height: var(--leading-relaxed);
}

/* Section Headers */
.section-header {
  text-align: center;
  margin-bottom: 3rem;
}

.section-header__eyebrow {
  font-size: var(--text-sm);
  font-weight: var(--weight-semibold);
  color: var(--color-primary);
  text-transform: uppercase;
  letter-spacing: 0.1em;
  margin-bottom: 0.75rem;
}

.section-header__headline {
  font-family: var(--font-heading);
  font-size: clamp(1.75rem, 3vw, 2.5rem);
  font-weight: var(--weight-bold);
  color: var(--color-text);
  margin-bottom: 0.75rem;
}

.section-header__subheadline {
  font-size: var(--text-base);
  color: var(--color-text-secondary);
  max-width: 640px;
  margin: 0 auto;
}

/* Testimonials */
.testimonial-card {
  padding: 2rem;
  background-color: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  margin-bottom: 1.5rem;
}

.testimonial-card__quote {
  font-size: var(--text-base);
  color: var(--color-text);
  line-height: var(--leading-relaxed);
  margin-bottom: 1.5rem;
  font-style: italic;
}

.testimonial-card__author {
  font-weight: var(--weight-semibold);
  color: var(--color-text);
  font-size: var(--text-sm);
}

.testimonial-card__role {
  color: var(--color-text-secondary);
  font-size: var(--text-sm);
}

/* CTA Banner */
.cta-banner {
  padding: 4rem 2rem;
  text-align: center;
  background-color: var(--color-primary);
  color: var(--color-text-on-primary);
  border-radius: var(--radius-xl);
}

.cta-banner__headline {
  font-family: var(--font-heading);
  font-size: clamp(1.5rem, 3vw, 2.25rem);
  font-weight: var(--weight-bold);
  margin-bottom: 0.75rem;
}

.cta-banner__subheadline {
  font-size: var(--text-base);
  opacity: 0.85;
  margin-bottom: 2rem;
}

/* Footer */
.footer {
  padding: 4rem 0 2rem;
  background-color: var(--color-surface);
  border-top: 1px solid var(--color-border);
}

.footer__grid {
  display: grid;
  grid-template-columns: 2fr repeat(3, 1fr);
  gap: 3rem;
  margin-bottom: 3rem;
}

.footer__brand-name {
  font-family: var(--font-heading);
  font-size: var(--text-xl);
  font-weight: var(--weight-bold);
  color: var(--color-text);
  margin-bottom: 0.75rem;
}

.footer__tagline {
  font-size: var(--text-sm);
  color: var(--color-text-secondary);
  line-height: var(--leading-relaxed);
}

.footer__column-title {
  font-weight: var(--weight-semibold);
  color: var(--color-text);
  font-size: var(--text-sm);
  margin-bottom: 1rem;
}

.footer__column-links {
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.footer__column-links a {
  color: var(--color-text-secondary);
  font-size: var(--text-sm);
}

.footer__bottom {
  padding-top: 2rem;
  border-top: 1px solid var(--color-border);
  text-align: center;
  font-size: var(--text-sm);
  color: var(--color-text-secondary);
}

/* Form */
.form {
  max-width: 640px;
  margin: 0 auto;
}

.form__field {
  margin-bottom: 1.5rem;
}

.form__label {
  display: block;
  font-size: var(--text-sm);
  font-weight: var(--weight-medium);
  color: var(--color-text);
  margin-bottom: 0.5rem;
}

.form__input,
.form__textarea {
  width: 100%;
  padding: 0.75rem 1rem;
  background-color: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  color: var(--color-text);
  font-family: var(--font-body);
  font-size: var(--text-base);
}

.form__textarea {
  min-height: 120px;
  resize: vertical;
}

/* Responsive */
@media (max-width: 768px) {
  .nav__links { display: none; }
  .footer__grid { grid-template-columns: 1fr; }
  .features-grid { grid-template-columns: 1fr; }
}
`;
}

function generateHTML(
  businessName: string,
  components: ComponentPlacement[],
  cssVars: Record<string, string>
): string {
  const fontFamilies = new Set<string>();
  const headingFont = cssVars["--font-heading"] || "'Inter', sans-serif";
  const bodyFont = cssVars["--font-body"] || "'Inter', sans-serif";

  // Extract font names for Google Fonts link
  for (const font of [headingFont, bodyFont]) {
    const match = font.match(/'([^']+)'/);
    if (match) fontFamilies.add(match[1]);
  }

  const fontsUrl =
    fontFamilies.size > 0
      ? `https://fonts.googleapis.com/css2?${Array.from(fontFamilies)
          .map((f) => `family=${f.replace(/\s+/g, "+")}:wght@400;500;600;700`)
          .join("&")}&display=swap`
      : "";

  const sections = components.map((c) => renderComponent(c, businessName)).join("\n\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(businessName)}</title>
  ${fontsUrl ? `<link rel="preconnect" href="https://fonts.googleapis.com">\n  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n  <link href="${fontsUrl}" rel="stylesheet">` : ""}
  <link rel="stylesheet" href="styles.css">
</head>
<body>
${sections}
</body>
</html>`;
}

function renderComponent(c: ComponentPlacement, businessName: string): string {
  const content = c.content as Record<string, unknown>;

  switch (c.componentId) {
    case "nav-sticky":
      return renderNav(content, businessName);
    case "hero-centered":
    case "hero-split":
      return renderHero(content);
    case "content-features":
      return renderFeatures(content);
    case "content-text":
      return renderTextBlock(content);
    case "content-stats":
      return renderStats(content);
    case "proof-testimonials":
      return renderTestimonials(content);
    case "cta-banner":
      return renderCtaBanner(content);
    case "form-contact":
      return renderContactForm(content);
    case "footer-standard":
      return renderFooter(content, businessName);
    case "commerce-services":
      return renderServices(content);
    case "team-grid":
      return renderTeam(content);
    case "content-accordion":
      return renderAccordion(content);
    case "content-logos":
      return renderLogos(content);
    case "pricing-table":
      return renderPricingTable(content);
    case "content-steps":
      return renderSteps(content);
    case "content-comparison":
      return renderComparison(content);
    case "hero-video":
      return renderHero(content);
    case "blog-preview":
      return renderBlogPreview(content);
    case "content-map":
      return renderMap(content);
    default:
      return `<!-- Component: ${c.componentId} (not yet supported in export) -->`;
  }
}

function renderNav(content: Record<string, unknown>, businessName: string): string {
  const logoText = (content.logoText as string) || businessName;
  const links = (content.links as Array<{ label: string; href: string }>) || [];
  const cta = content.cta as { text: string; href: string } | undefined;

  return `  <nav class="nav">
    <div class="container">
      <a href="#" class="nav__logo">${escapeHtml(logoText)}</a>
      <ul class="nav__links">
        ${links.map((l) => `<li><a href="${escapeHtml(l.href)}">${escapeHtml(l.label)}</a></li>`).join("\n        ")}
      </ul>
      ${cta ? `<a href="${escapeHtml(cta.href)}" class="nav__cta">${escapeHtml(cta.text)}</a>` : ""}
    </div>
  </nav>`;
}

function renderHero(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const subheadline = (content.subheadline as string) || "";
  const ctaPrimary = content.ctaPrimary as { text: string; href: string } | undefined;
  const ctaSecondary = content.ctaSecondary as { text: string; href: string } | undefined;

  return `  <section class="hero">
    <div class="container">
      <h1 class="hero__headline">${escapeHtml(headline)}</h1>
      ${subheadline ? `<p class="hero__subheadline">${escapeHtml(subheadline)}</p>` : ""}
      <div class="hero__actions">
        ${ctaPrimary ? `<a href="${escapeHtml(ctaPrimary.href)}" class="btn-primary">${escapeHtml(ctaPrimary.text)}</a>` : ""}
        ${ctaSecondary ? `<a href="${escapeHtml(ctaSecondary.href)}" class="btn-outline">${escapeHtml(ctaSecondary.text)}</a>` : ""}
      </div>
    </div>
  </section>`;
}

function renderFeatures(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const subheadline = (content.subheadline as string) || "";
  const features = (content.features as Array<{ title: string; description: string }>) || [];

  return `  <section class="section" id="services">
    <div class="container">
      <div class="section-header">
        ${subheadline ? `<p class="section-header__eyebrow">${escapeHtml(subheadline)}</p>` : ""}
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
      </div>
      <div class="features-grid">
        ${features
          .map(
            (f) => `<div class="feature-card">
          <h3 class="feature-card__title">${escapeHtml(f.title)}</h3>
          <p class="feature-card__description">${escapeHtml(f.description)}</p>
        </div>`
          )
          .join("\n        ")}
      </div>
    </div>
  </section>`;
}

function renderTextBlock(content: Record<string, unknown>): string {
  const eyebrow = content.eyebrow as string | undefined;
  const headline = (content.headline as string) || "";
  const body = (content.body as string) || "";
  const id = (content.id as string) || "";

  return `  <section class="section section--alt"${id ? ` id="${escapeHtml(id)}"` : ""}>
    <div class="container">
      <div class="section-header">
        ${eyebrow ? `<p class="section-header__eyebrow">${escapeHtml(eyebrow)}</p>` : ""}
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
        <div class="section-header__subheadline">${body}</div>
      </div>
    </div>
  </section>`;
}

function renderStats(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const stats =
    (content.stats as Array<{ value: string; label: string; suffix?: string; prefix?: string }>) ||
    [];

  return `  <section class="section">
    <div class="container">
      ${headline ? `<div class="section-header"><h2 class="section-header__headline">${escapeHtml(headline)}</h2></div>` : ""}
      <div class="features-grid" style="text-align: center;">
        ${stats
          .map(
            (s) => `<div class="feature-card" style="text-align: center;">
          <div style="font-family: var(--font-heading); font-size: clamp(2rem, 4vw, 3rem); font-weight: var(--weight-bold); color: var(--color-primary);">${escapeHtml(s.prefix || "")}${escapeHtml(s.value)}${escapeHtml(s.suffix || "")}</div>
          <p class="feature-card__description">${escapeHtml(s.label)}</p>
        </div>`
          )
          .join("\n        ")}
      </div>
    </div>
  </section>`;
}

function renderTestimonials(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const testimonials =
    (content.testimonials as Array<{ quote: string; name: string; role: string }>) || [];

  return `  <section class="section section--alt" id="testimonials">
    <div class="container">
      <div class="section-header">
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
      </div>
      <div class="features-grid">
        ${testimonials
          .map(
            (t) => `<div class="testimonial-card">
          <p class="testimonial-card__quote">"${escapeHtml(t.quote)}"</p>
          <p class="testimonial-card__author">${escapeHtml(t.name)}</p>
          <p class="testimonial-card__role">${escapeHtml(t.role)}</p>
        </div>`
          )
          .join("\n        ")}
      </div>
    </div>
  </section>`;
}

function renderCtaBanner(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const subheadline = (content.subheadline as string) || "";
  const ctaPrimary = content.ctaPrimary as { text: string; href: string } | undefined;

  return `  <section class="section">
    <div class="container">
      <div class="cta-banner">
        <h2 class="cta-banner__headline">${escapeHtml(headline)}</h2>
        ${subheadline ? `<p class="cta-banner__subheadline">${escapeHtml(subheadline)}</p>` : ""}
        ${ctaPrimary ? `<a href="${escapeHtml(ctaPrimary.href)}" class="btn-primary" style="background: var(--color-text-on-primary); color: var(--color-primary);">${escapeHtml(ctaPrimary.text)}</a>` : ""}
      </div>
    </div>
  </section>`;
}

function renderContactForm(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "Get in Touch";
  const subheadline = (content.subheadline as string) || "";
  const fields = (content.fields as Array<{ name: string; label: string; type: string }>) || [
    { name: "name", label: "Your Name", type: "text" },
    { name: "email", label: "Email Address", type: "email" },
    { name: "message", label: "Message", type: "textarea" },
  ];
  const submitText = (content.submitText as string) || "Send Message";
  const id = (content.id as string) || "contact";

  return `  <section class="section" id="${escapeHtml(id)}">
    <div class="container">
      <div class="section-header">
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
        ${subheadline ? `<p class="section-header__subheadline">${escapeHtml(subheadline)}</p>` : ""}
      </div>
      <form class="form" action="#" method="POST">
        ${fields
          .map((f) =>
            f.type === "textarea"
              ? `<div class="form__field">
          <label class="form__label" for="${escapeHtml(f.name)}">${escapeHtml(f.label)}</label>
          <textarea class="form__textarea" id="${escapeHtml(f.name)}" name="${escapeHtml(f.name)}" placeholder="${escapeHtml(f.label)}"></textarea>
        </div>`
              : `<div class="form__field">
          <label class="form__label" for="${escapeHtml(f.name)}">${escapeHtml(f.label)}</label>
          <input class="form__input" type="${escapeHtml(f.type)}" id="${escapeHtml(f.name)}" name="${escapeHtml(f.name)}" placeholder="${escapeHtml(f.label)}">
        </div>`
          )
          .join("\n        ")}
        <button type="submit" class="btn-primary" style="width: 100%;">${escapeHtml(submitText)}</button>
      </form>
    </div>
  </section>`;
}

function renderFooter(content: Record<string, unknown>, businessName: string): string {
  const logoText = (content.logoText as string) || businessName;
  const tagline = (content.tagline as string) || "";
  const columns =
    (content.columns as Array<{ title: string; links: Array<{ label: string; href: string }> }>) ||
    [];
  const copyright =
    (content.copyright as string) ||
    `${new Date().getFullYear()} ${businessName}. All rights reserved.`;

  return `  <footer class="footer">
    <div class="container">
      <div class="footer__grid">
        <div>
          <div class="footer__brand-name">${escapeHtml(logoText)}</div>
          ${tagline ? `<p class="footer__tagline">${escapeHtml(tagline)}</p>` : ""}
        </div>
        ${columns
          .map(
            (col) => `<div>
          <h4 class="footer__column-title">${escapeHtml(col.title)}</h4>
          <ul class="footer__column-links">
            ${col.links.map((l) => `<li><a href="${escapeHtml(l.href)}">${escapeHtml(l.label)}</a></li>`).join("\n            ")}
          </ul>
        </div>`
          )
          .join("\n        ")}
      </div>
      <div class="footer__bottom">
        <p>&copy; ${escapeHtml(copyright)}</p>
      </div>
    </div>
  </footer>`;
}

function renderServices(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const subheadline = (content.subheadline as string) || "";
  const services =
    (content.services as Array<{
      title: string;
      description: string;
      price?: string;
      featured?: boolean;
    }>) || [];

  return `  <section class="section section--alt">
    <div class="container">
      <div class="section-header">
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
        ${subheadline ? `<p class="section-header__subheadline">${escapeHtml(subheadline)}</p>` : ""}
      </div>
      <div class="features-grid">
        ${services
          .map(
            (
              s
            ) => `<div class="feature-card"${s.featured ? ' style="border-color: var(--color-primary);"' : ""}>
          ${s.price ? `<div style="font-size: var(--text-2xl); font-weight: var(--weight-bold); color: var(--color-primary); margin-bottom: 0.5rem;">${escapeHtml(s.price)}</div>` : ""}
          <h3 class="feature-card__title">${escapeHtml(s.title)}</h3>
          <p class="feature-card__description">${escapeHtml(s.description)}</p>
        </div>`
          )
          .join("\n        ")}
      </div>
    </div>
  </section>`;
}

function renderTeam(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const subheadline = (content.subheadline as string) || "";
  const members = (content.members as Array<{ name: string; role: string; bio?: string }>) || [];

  return `  <section class="section">
    <div class="container">
      <div class="section-header">
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
        ${subheadline ? `<p class="section-header__subheadline">${escapeHtml(subheadline)}</p>` : ""}
      </div>
      <div class="features-grid">
        ${members
          .map(
            (m) => `<div class="feature-card" style="text-align: center;">
          <div style="width: 80px; height: 80px; border-radius: 50%; background: var(--color-primary); margin: 0 auto 1rem; display: flex; align-items: center; justify-content: center; color: var(--color-text-on-primary); font-weight: var(--weight-bold); font-size: var(--text-xl);">${escapeHtml(m.name.charAt(0))}</div>
          <h3 class="feature-card__title">${escapeHtml(m.name)}</h3>
          <p style="color: var(--color-primary); font-size: var(--text-sm); margin-bottom: 0.5rem;">${escapeHtml(m.role)}</p>
          ${m.bio ? `<p class="feature-card__description">${escapeHtml(m.bio)}</p>` : ""}
        </div>`
          )
          .join("\n        ")}
      </div>
    </div>
  </section>`;
}

function renderAccordion(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const items = (content.items as Array<{ question: string; answer: string }>) || [];

  return `  <section class="section section--alt">
    <div class="container">
      <div class="section-header">
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
      </div>
      <div style="max-width: 800px; margin: 0 auto;">
        ${items
          .map(
            (
              item
            ) => `<details style="border: 1px solid var(--color-border); border-radius: var(--radius-md); margin-bottom: 0.75rem; overflow: hidden;">
          <summary style="padding: 1.25rem 1.5rem; cursor: pointer; font-weight: var(--weight-semibold); color: var(--color-text); background: var(--color-surface);">${escapeHtml(item.question)}</summary>
          <div style="padding: 1rem 1.5rem; color: var(--color-text-secondary); line-height: var(--leading-relaxed);">${item.answer}</div>
        </details>`
          )
          .join("\n        ")}
      </div>
    </div>
  </section>`;
}

function renderLogos(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const logos = (content.logos as Array<{ name: string }>) || [];

  return `  <section class="section" style="padding: var(--space-component) 0;">
    <div class="container">
      ${headline ? `<div class="section-header"><p class="section-header__eyebrow">${escapeHtml(headline)}</p></div>` : ""}
      <div style="display: flex; flex-wrap: wrap; gap: 3rem; justify-content: center; align-items: center; opacity: 0.5;">
        ${logos.map((l) => `<span style="font-family: var(--font-heading); font-size: var(--text-lg); font-weight: var(--weight-semibold); color: var(--color-text-secondary);">${escapeHtml(l.name)}</span>`).join("\n        ")}
      </div>
    </div>
  </section>`;
}

function renderPricingTable(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const subheadline = (content.subheadline as string) || "";
  const plans =
    (content.plans as Array<{
      name: string;
      price: string;
      period?: string;
      features?: Array<{ text: string; included: boolean }>;
      featured?: boolean;
    }>) || [];

  return `  <section class="section section--alt">
    <div class="container">
      <div class="section-header">
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
        ${subheadline ? `<p class="section-header__subheadline">${escapeHtml(subheadline)}</p>` : ""}
      </div>
      <div class="features-grid">
        ${plans
          .map(
            (
              p
            ) => `<div class="feature-card"${p.featured ? ' style="border-color: var(--color-primary); transform: scale(1.02);"' : ""}>
          <h3 class="feature-card__title">${escapeHtml(p.name)}</h3>
          <div style="font-family: var(--font-heading); font-size: clamp(2rem, 4vw, 3rem); font-weight: var(--weight-bold); color: var(--color-primary); margin: 0.5rem 0;">${escapeHtml(p.price)}${p.period ? `<span style="font-size: var(--text-sm); color: var(--color-text-secondary);">${escapeHtml(p.period)}</span>` : ""}</div>
          ${
            p.features
              ? `<ul style="list-style: none; padding: 0; margin: 1rem 0;">
            ${p.features.map((f) => `<li style="padding: 0.25rem 0; color: ${f.included ? "var(--color-text)" : "var(--color-text-secondary)"};">${f.included ? "✓" : "✗"} ${escapeHtml(f.text)}</li>`).join("\n            ")}
          </ul>`
              : ""
          }
        </div>`
          )
          .join("\n        ")}
      </div>
    </div>
  </section>`;
}

function renderSteps(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const subheadline = (content.subheadline as string) || "";
  const steps = (content.steps as Array<{ title: string; description: string }>) || [];

  return `  <section class="section">
    <div class="container">
      <div class="section-header">
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
        ${subheadline ? `<p class="section-header__subheadline">${escapeHtml(subheadline)}</p>` : ""}
      </div>
      <div style="max-width: 700px; margin: 0 auto;">
        ${steps
          .map(
            (
              s,
              i
            ) => `<div style="display: flex; gap: 1.5rem; margin-bottom: 2rem; align-items: flex-start;">
          <div style="width: 40px; height: 40px; border-radius: 50%; background: var(--color-primary); color: var(--color-text-on-primary); display: flex; align-items: center; justify-content: center; font-weight: var(--weight-bold); flex-shrink: 0;">${i + 1}</div>
          <div>
            <h3 class="feature-card__title">${escapeHtml(s.title)}</h3>
            <p class="feature-card__description">${escapeHtml(s.description)}</p>
          </div>
        </div>`
          )
          .join("\n        ")}
      </div>
    </div>
  </section>`;
}

function renderComparison(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const columns = (content.columns as Array<{ name: string }>) || [];
  const rows = (content.rows as Array<{ feature: string; values: (string | boolean)[] }>) || [];

  return `  <section class="section section--alt">
    <div class="container">
      <div class="section-header">
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
      </div>
      <div style="overflow-x: auto;">
        <table style="width: 100%; border-collapse: collapse; text-align: left;">
          <thead>
            <tr>
              <th style="padding: 1rem; border-bottom: 2px solid var(--color-border); font-weight: var(--weight-semibold);">Feature</th>
              ${columns.map((c) => `<th style="padding: 1rem; border-bottom: 2px solid var(--color-border); font-weight: var(--weight-semibold); text-align: center;">${escapeHtml(c.name)}</th>`).join("\n              ")}
            </tr>
          </thead>
          <tbody>
            ${rows
              .map(
                (r) => `<tr>
              <td style="padding: 0.75rem 1rem; border-bottom: 1px solid var(--color-border-light);">${escapeHtml(r.feature)}</td>
              ${r.values.map((v) => `<td style="padding: 0.75rem 1rem; border-bottom: 1px solid var(--color-border-light); text-align: center;">${typeof v === "boolean" ? (v ? "✓" : "✗") : escapeHtml(String(v))}</td>`).join("\n              ")}
            </tr>`
              )
              .join("\n            ")}
          </tbody>
        </table>
      </div>
    </div>
  </section>`;
}

function renderBlogPreview(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const posts =
    (content.posts as Array<{ title: string; excerpt: string; date?: string; author?: string }>) ||
    [];

  return `  <section class="section">
    <div class="container">
      <div class="section-header">
        <h2 class="section-header__headline">${escapeHtml(headline)}</h2>
      </div>
      <div class="features-grid">
        ${posts
          .map(
            (p) => `<div class="feature-card">
          <div style="background: linear-gradient(135deg, var(--color-primary), var(--color-surface)); height: 160px; border-radius: var(--radius-md); margin-bottom: 1rem;"></div>
          <h3 class="feature-card__title">${escapeHtml(p.title)}</h3>
          <p class="feature-card__description">${escapeHtml(p.excerpt)}</p>
          ${p.date || p.author ? `<p style="font-size: var(--text-sm); color: var(--color-text-secondary); margin-top: 0.75rem;">${p.date ? escapeHtml(p.date) : ""}${p.date && p.author ? " · " : ""}${p.author ? escapeHtml(p.author) : ""}</p>` : ""}
        </div>`
          )
          .join("\n        ")}
      </div>
    </div>
  </section>`;
}

function renderMap(content: Record<string, unknown>): string {
  const headline = (content.headline as string) || "";
  const contactInfo = content.contactInfo as
    | {
        address?: string;
        phone?: string;
        email?: string;
        hours?: string[];
      }
    | undefined;

  return `  <section class="section section--alt">
    <div class="container">
      ${headline ? `<div class="section-header"><h2 class="section-header__headline">${escapeHtml(headline)}</h2></div>` : ""}
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 3rem;">
        <div style="background: linear-gradient(135deg, var(--color-surface), var(--color-surface-elevated)); height: 300px; border-radius: var(--radius-lg); display: flex; align-items: center; justify-content: center; color: var(--color-text-secondary);">
          📍 Map Placeholder
        </div>
        ${
          contactInfo
            ? `<div style="display: flex; flex-direction: column; gap: 1.5rem; justify-content: center;">
          ${contactInfo.address ? `<div><strong>Address</strong><br>${escapeHtml(contactInfo.address)}</div>` : ""}
          ${contactInfo.phone ? `<div><strong>Phone</strong><br><a href="tel:${escapeHtml(contactInfo.phone)}">${escapeHtml(contactInfo.phone)}</a></div>` : ""}
          ${contactInfo.email ? `<div><strong>Email</strong><br><a href="mailto:${escapeHtml(contactInfo.email)}">${escapeHtml(contactInfo.email)}</a></div>` : ""}
          ${contactInfo.hours ? `<div><strong>Hours</strong><br>${contactInfo.hours.map((h) => escapeHtml(h)).join("<br>")}</div>` : ""}
        </div>`
            : ""
        }
      </div>
    </div>
  </section>`;
}

function generateReadme(businessName: string): string {
  return `# ${businessName}

Generated by [EasyWebsiteBuild](https://easywebsitebuild.com)

## Getting Started

1. Open \`index.html\` in your browser to preview the site
2. Edit \`styles.css\` to customize colors, fonts, and spacing
3. Modify \`index.html\` to update content

## Files

- \`index.html\` — Main page with all sections
- \`styles.css\` — Theme variables and component styles
- \`README.md\` — This file

## Customization

All visual values are driven by CSS custom properties in \`:root\`.
Edit the variables at the top of \`styles.css\` to change:

- Colors (--color-*)
- Typography (--font-*, --text-*, --weight-*)
- Spacing (--space-*)
- Border radius (--radius-*)

## Deployment

This is a static site — deploy to any hosting provider:

- [Vercel](https://vercel.com)
- [Netlify](https://netlify.com)
- [GitHub Pages](https://pages.github.com)

Simply drag and drop the files or connect your repository.
`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
